//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChistyulyaStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesRole
    {
        public EmployeesRole()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int ID_EmployeeRole { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
    }
}
