//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChistyulyaStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int ID_Product { get; set; }
        public int ID_Unit { get; set; }
        public int ID_Supplier { get; set; }
        public int ID_Manufacturer { get; set; }
        public int ID_Category { get; set; }
        public string Article { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public int Discount { get; set; }
        public int StockQuantity { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public byte[] ProductImage { get; set; }
        public string ImageType { get; set; }
        public Nullable<System.DateTime> ImageLastUpdated { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual UnitsOfMeasurement UnitsOfMeasurement { get; set; }
    }
}
